select * from customer limit 200;


-- 1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue from customer group by gender;



-- 2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where purchase_amount >= (select avg(purchase_amount) from customer) and discount_applied = 'Yes'



-- 3. Which are the top 5 products with the highest average review rating
select item_purchased, Round(avg(review_rating)::numeric,2) as Avg_product_rating
from customer
group by item_purchased order by avg(review_rating) desc limit 5



-- 4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, Round(avg(purchase_amount),2) as Avg_purchase_amt
from customer where shipping_type in ('Standard','Express')
group by shipping_type 



-- Q5. Do subscribed customers spend more? 
-- Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id)as total_customers, 
Round(avg(purchase_amount),2) as avg_spend, 
Round(sum(purchase_amount),2) as total_revenue 
from customer group by subscription_status
order by avg_spend,total_revenue desc



-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
Round((sum(case when discount_applied = 'Yes' then 1 else 0 end) * 100) / count(*),2) as perc_purchase
from customer
group by item_purchased  order by perc_purchase desc limit 5



--07. Segment customers into New, Returning, and Loyal based on their total
--number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id,previous_purchases,
case 
     when previous_purchases = 1 then 'New'
     when previous_purchases between 2 and 10 then 'Returning'
	 else 'Loyal'
	 end as customer_segment
from customer
)
select customer_segment, count(*) as segment_cnt
from customer_type group by customer_segment 



-- 8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,item_purchased,count(customer_id) as tot_purchase, 
Row_number() over(partition by category order by count(customer_id) desc) as ranks
from customer group by item_purchased,category
) 
select * from item_counts where ranks<4



-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as tol_customers from customer 
where previous_purchases>5 group by subscription_status



-- 10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as revenue 
from customer
group by age_group order by revenue desc













